### ISSUE TITLE
bats org

### ISSUE THREAD

**Issue by jasonkarns** [ztombol/bats-docs#11]
Any thoughts or plans on creating a bats org for -docs, -support, -assert, and -file?

Aside from the benefit of adding maintainers to the org/repos, a side benefit is the ability to use waffle.io.

I've used waffle.io as a multi-repo kanban board for managing Issues on a number of projects and it works quite well. All issue information is kept in github, so its use is optional (anyone can continue to use the issues through GitHub without consequence). But for those who choose to do so, it's possible to view the issues on a kanban-like board with the best part being that you can view all of the issues across numerous repos. So we could add all the bats-\* repos to the board and have a single place to view the status of all issues/prs across the "org".

**Comment by ztombol** [comment]
I haven't used waffle.io yet, but it looks very convenient! I'd love to use it, but I think that the decision to create an organisation using Bats' name belongs to @sstephenson.

A different name maybe? Organisations can be renamed on GitHub and I suspect that waffle.io can handle the change (or even the reassigning of repositories to an official Bats organisation eventually). What do you think?

Although I was optimistic in the beginning, seeing that not much work has been done on long standing issues since the call for maintainers has been put out, I'm not sure what the future of Bats is. I know fully well that life happens and everybody is busy. I didn't post that list of improvements I promised months ago either.

I'm planning to work through your contributions first, and then complete that long promised list for Bats. If no discussion happens around that list, I will be tempted to say we need a fork.

**Comment by jasonkarns** [comment]
discussion here: https://github.com/bats-core/bats-core/issues/44
