### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jasonkarns** [ztombol/bats-docs#6]
I realize there was already a license discussion. A slight wrinkle that I uncovered when attempting to add the `CC0` license to the package.json metadata: `CC0` is not an OSI-approved OSS license

see: https://opensource.org/faq#cc-zero

I'm not suggesting this warrants a license change, but it's a concern. The only practical implication at the moment is that `CC0` is invalid as the value for the `license` field in `package.json`.

**Comment by ztombol** [comment]
Like I've said before, I'm not familiar with npm. I only took a quick look at the [documentation](https://docs.npmjs.com/files/package.json#license), but it doesn't seem to forbid non-approced licences. As per the [list of SPDX licence IDs](https://spdx.org/licenses/), the correct value is `CC0-1.0`. Or did I misunderstand something?

**Comment by ztombol** [comment]
The confusion over naming and choosing a possibly less than optimal licence are all caused by the rushed release. I didn't leave enough time to discuss naming and licensing. I had less and less time to work on these libraries, and just wanted them out the door. Lesson learned. :)

I was aware that CC0 is not an OSI approved licence, but at the time that seemed to be the only one that ensured compatibility.

OSI didn't approve CC0 because it doesn't waive or licence patents (and also because according to them the [public domain is not appropriate for open source software][osi-pub-dom]). The libraries are, and will always be, so simple I don't think there would be any patents to be claimed (not that I wanted to). Though, I understand this is no legal assurance.

Working against the proliferation of licences by using an OSI approved licence would have been better too.

We are still early in development, so if we commit to sort the licence issue out we should do it as soon as possible. There are two questions I can see.
- **Is the licence compatibility assumption really correct?** We need legal advice to answer this.
- **Even if it is not, why not side with OSI?** The public domain is no place for open source software. Let's choose an OSI approved permissive licence. Even if we lose compatibility with the public domain, open source software shouldn't be there in the first place.

My knowledge and experience is very limited on licensing. So this is something that we need to figure out together. Possibly with legal advice from someone knowledgeable in the field, e.g. OSI or FSF.

**Comment by jasonkarns** [comment]
> As per the list of SPDX licence IDs, the correct value is CC0-1.0

doh, thanks. My main point was just to make sure you were aware that CC0 wasn't approved by OSI. But you are, and I agree that the reasons for its exclusion don't matter here.
